platform :ios, "10.0"
use_modular_headers!

project 'TokenCore.xcodeproj'
target 'TokenCore_Example' do
  
  pod 'TokenCore', :path => '../'
#  pod "TokenCore", git: "https://github.com/coinslabs/token-core-ios.git"
  pod 'PureLayout'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod 'CoreBitcoin', :path => '../Vendor'
  pod 'libscrypt'

end
